// Generated by CoffeeScript 1.8.0
var mqtt;

mqtt = require('mqtt');

console.log("Loading event");

exports.handler = function(event, context) {
  var client, i, _i;
  console.log("event =\n", event);
  client = mqtt.connect("mqtt://test.mosquitto.org:1883");
  console.log("after mqtt.connect()");
  for (i = _i = 1; _i <= 1000; i = ++_i) {
    console.log("before client.publish() ", i);
    client.publish(event.topic, event.value, {
      retain: (event.retain != null) && event.retain
    });
    console.log("after client.publish()", i);
  }
  client.end();
  console.log("after cleint.end()");
  client.on("close", (function() {
    return context.done(null, "SUCCESS");
  }));
  client.on("error", (function() {
    return context.done(null, "SUCCESS");
  }));
};
